service: karmabot-tutorial

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6

functions:
  event_receive:
    handler: karmabot/event.receive
    memorySize: 128
    events:
      - http:
          path: event/receive
          method: post
          cors: true